chore: retry steps if failed

diff --git a/.github/workflows/nvchecker.yml b/.github/workflows/nvchecker.yml
--- a/.github/workflows/nvchecker.yml
+++ b/.github/workflows/nvchecker.yml
@@ -21,26 +21,37 @@ jobs:
 
     - name: gentoo
       run: |
-        # eselect
-        echo "::group::eselect repository add and sync"
-        eselect repository enable dlang
-        emerge --sync dlang
-        repo_name=$(cat profiles/repo_name)
-        eselect repository add "$repo_name" git "file://${PWD}"
-        emerge --sync "$repo_name"
-        egencache --jobs=$(nproc) --update --repo "$repo_name" &> /dev/null
-        eix-update
-        echo "::endgroup::"
-        # eix
-        echo "::group::eix search packages"
-        pkgs=$(ACCEPT_LICENSE="*" ACCEPT_KEYWORDS="~amd64 ~arm64 ~loong ~riscv" EIX_LIMIT=0 NAMEVERSION="<category>/<name>-<version>\n" eix --pure-packages --in-overlay "$repo_name" --format '<bestversion:NAMEVERSION>')
-        pkgs=$(qatom -F "\"%{CATEGORY}/%{PN}\": \"%{PV}\"," $pkgs) # remove revision
-        echo "$pkgs"
-        pkgs="{ ${pkgs::-1} }"
-        echo "$pkgs" > .github/workflows/old_ver.json
-        # sed -r -i 's/_p[^"]*//' .github/workflows/old_ver.json
-        cat .github/workflows/old_ver.json
-        echo "::endgroup::"
+        for i in {1..100}; do
+          (
+            set -e
+            # eselect
+            echo "::group::eselect repository add and sync"
+            eselect repository enable dlang
+            emerge --sync dlang
+            repo_name=$(cat profiles/repo_name)
+            eselect repository add "$repo_name" git "file://${PWD}"
+            emerge --sync "$repo_name"
+            egencache --jobs=$(nproc) --update --repo "$repo_name" &> /dev/null
+            eix-update
+            echo "::endgroup::"
+            # eix
+            echo "::group::eix search packages"
+            pkgs=$(ACCEPT_LICENSE="*" ACCEPT_KEYWORDS="~amd64 ~arm64 ~loong ~riscv" EIX_LIMIT=0 NAMEVERSION="<category>/<name>-<version>\n" eix --pure-packages --in-overlay "$repo_name" --format '<bestversion:NAMEVERSION>')
+            pkgs=$(qatom -F "\"%{CATEGORY}/%{PN}\": \"%{PV}\"," $pkgs) # remove revision
+            echo "$pkgs"
+            pkgs="{ ${pkgs::-1} }"
+            echo "$pkgs" > .github/workflows/old_ver.json
+            # sed -r -i 's/_p[^"]*//' .github/workflows/old_ver.json
+            cat .github/workflows/old_ver.json
+            echo "::endgroup::"
+          ) && break
+          echo "Attempt $i failed! Retrying in 5 seconds..."
+          sleep 5
+        done
+        if [ $i -eq 100 ]; then
+          echo "All 100 attempts failed."
+          exit 1
+        fi
 
     - name: nvchecker
       id: nvchecker
